complex_server: complex_server.c
	gcc -o complex_server complex_server.c -lpthread

modsimple_client: modsimple_client.c
	gcc -o modsimple_client modsimple_client.c

all: complex_server modsimple_client